In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
normal = pd.read_csv('c:/Users/ASUS/Desktop/ptbdb_normal.csv')
abnormal = pd.read_csv('c:/Users/ASUS/Desktop/ptbdb_abnormal.csv')

In [3]:
new_column_name = []
for num in range(abnormal.shape[1]-1):
    tem = 'time' + str(num)
    new_column_name.append(tem)
new_column_name.append("Label")    #label = 1 for abnormal
abnormal.columns = new_column_name    


column_name = []
for num in range(normal.shape[1]-1):
    tem = 'time' + str(num)
    column_name.append(tem)
column_name.append("Label")    #label = 0 for normal
normal.columns = column_name

abnormal.head()

,time0,time1,time2,time3,time4,time5,time6,time7,time8,time9,...,time178,time179,time180,time181,time182,time183,time184,time185,time186,Label
0,1.000000,0.606941,0.384181,0.254237,0.223567,0.276836,0.253430,0.184826,0.153349,0.121872,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.000000,0.951613,0.923963,0.853303,0.791859,0.734255,0.672043,0.685100,0.670507,0.667435,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.977819,0.899261,0.230129,0.032348,0.142329,0.223660,0.328096,0.367837,0.381701,0.389094,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.935618,0.801661,0.805815,1.000000,0.722741,0.480789,0.454829,0.319834,0.266874,0.308411,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.925265,0.433352,0.073620,0.079197,0.136643,0.182934,0.182934,0.182376,0.196877,0.203569,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [4]:
data=[normal,abnormal]
data=pd.concat(data)

In [5]:
from sklearn.utils import shuffle
data=shuffle(data)                 
data.head()

,time0,time1,time2,time3,time4,time5,time6,time7,time8,time9,...,time178,time179,time180,time181,time182,time183,time184,time185,time186,Label
2440,0.951248,0.597214,0.251016,0.110273,0.099826,0.049333,0.031631,0.016251,0.010157,0.005514,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9516,1.000000,0.446569,0.385827,0.145669,0.138358,0.152981,0.136670,0.129359,0.142295,0.127109,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4230,1.000000,0.700961,0.114835,0.072486,0.095609,0.110158,0.120551,0.111458,0.118213,0.114575,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3359,0.976936,1.000000,0.683690,0.401977,0.245470,0.151565,0.217463,0.149918,0.157331,0.104613,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6274,0.966913,0.839654,0.449733,0.169509,0.127259,0.126241,0.098498,0.082718,0.073556,0.076101,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [6]:
y = data["Label"].values   # our labels.

data.drop(["Label"],axis=1,inplace=True)  

x = data  # our features..


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [7]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=186,metric='minkowski')

knn.fit(x_train,y_train.ravel())

result = knn.predict(x_test)

# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,result)
print(cm)

# Accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, result)
# SonuÃ§ : 0.98
print(accuracy)

[[ 432  333]
 [ 211 1934]]
0.8130584192439863