In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
normal = pd.read_csv('c:/Users/ASUS/Desktop/ptbdb_normal.csv')
abnormal = pd.read_csv('c:/Users/ASUS/Desktop/ptbdb_abnormal.csv')

In [4]:
new_column_name = []
for num in range(abnormal.shape[1]-1):
    tem = 'time' + str(num)
    new_column_name.append(tem)
new_column_name.append("Label")    #label = 1 for abnormal
abnormal.columns = new_column_name    


column_name = []
for num in range(normal.shape[1]-1):
    tem = 'time' + str(num)
    column_name.append(tem)
column_name.append("Label")    #label = 0 for normal
normal.columns = column_name

abnormal.head()

,time0,time1,time2,time3,time4,time5,time6,time7,time8,time9,...,time178,time179,time180,time181,time182,time183,time184,time185,time186,Label
0,1.000000,0.606941,0.384181,0.254237,0.223567,0.276836,0.253430,0.184826,0.153349,0.121872,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.000000,0.951613,0.923963,0.853303,0.791859,0.734255,0.672043,0.685100,0.670507,0.667435,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.977819,0.899261,0.230129,0.032348,0.142329,0.223660,0.328096,0.367837,0.381701,0.389094,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.935618,0.801661,0.805815,1.000000,0.722741,0.480789,0.454829,0.319834,0.266874,0.308411,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.925265,0.433352,0.073620,0.079197,0.136643,0.182934,0.182934,0.182376,0.196877,0.203569,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [5]:
data=[normal,abnormal]
data=pd.concat(data)

In [6]:
from sklearn.utils import shuffle
data=shuffle(data)                 
data.head()

,time0,time1,time2,time3,time4,time5,time6,time7,time8,time9,...,time178,time179,time180,time181,time182,time183,time184,time185,time186,Label
6387,1.000000,0.988817,0.846022,0.824516,0.763871,0.846022,0.799140,0.708817,0.693763,0.680860,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
565,1.000000,0.590543,0.420523,0.263078,0.199195,0.154930,0.114688,0.082495,0.086016,0.080483,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1756,0.994932,0.812669,0.291723,0.000000,0.052872,0.093243,0.128547,0.119764,0.126858,0.114189,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2441,1.000000,0.813333,0.330909,0.151515,0.000000,0.036364,0.253939,0.452727,0.463636,0.480606,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5890,0.970312,0.723437,0.703125,0.848437,0.694531,0.646094,0.625000,0.653906,0.646094,0.592969,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [10]:
y = data["Label"].values   # our labels.

data.drop(["Label"],axis=1,inplace=True)  

x = data  # our features.

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [11]:
from sklearn.svm import SVC

In [12]:
svc = SVC(kernel = 'poly')

In [13]:
svc.fit(x_train,y_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [14]:
result = svc.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,result)
print(cm)

# Accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, result)
print(accuracy)

[[   0  831]
 [   0 2079]]
0.7144329896907217